version: "3"

networks:
  stack_ponte:
    external: true

services:

  frontend_feeder:
    container_name: "frontend_feeder"
    image: "node:lts-alpine"
    working_dir: /app
    volumes:
      - "${PATHCLIENTES}/feeder/front:/app"
    command: "yarn dev"
    networks:
      - stack_ponte
    ports:
      - "3081:3000"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.frontfeeder.rule=Host(`frontfeeder.${DOMAIN}`)
      - traefik.http.services.frontfeeder.loadbalancer.server.port=3000
