version: "3"

networks:
  stack_ponte:
    external: true

services:
  frontend_feeder:
    container_name: "frontend_feeder"
    image: "node:lts-alpine"
    working_dir: /app
    volumes:
      - "${PATHCLIENTES}/feeder/frontend:/app"
    command: "yarn dev"
    networks:
      - stack_ponte
    ports:
      - "3077:3000"
