version: "3"

networks:
  stack_ponte:
    external: true

services:
  golangacolher:
    container_name: "golangacolher"
    image: golang:1.17.6
    working_dir: /app
    volumes:
      - /mnt/wolf/files/Developer/instituto_acolher/backgo:/app
      # - ${GOPATH}:/go
    ports:
      - "3030:8000"
    networks:
      - stack_ponte
    command: "/bin/sh -c 'go install github.com/cespare/reflex@latest && cd /app && reflex -c /app/reflex.conf'"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.gobackacolher.rule=Host(`gobackacolher.${DOMAIN}`)
      - traefik.http.services.gobackacolher.loadbalancer.server.port=8000
