version: "3"

networks:
  stack_ponte:
    external: true

services:

  frontend_feeder:
    container_name: "frontend_feede"
    image: "node:lts"
    working_dir: /app
    volumes:
      - "${DEVPATHCLIENTES}/feeder/frontend:/app"
    command: "yarn dev"
    networks:
      - stack_ponte
    ports:
      - "3077:3082"
